# Generated by Django 4.2.13 on 2024-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0002_rename_category_name_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('ARTI', 'Статья'), ('NEWS', 'Новость')], max_length=4),
        ),
    ]
